# This is an autogenerated function, ported from the original legacy version.
# It /should work/ as is, but will not have all the benefits of the modern
# function API. You should see the function docs to learn how to add function
# signatures for type safety and to document this function using puppet-strings.
#
# https://puppet.com/docs/puppet/latest/custom_functions_ruby.html
#
# ---- original file header ----
# Build dependency list for systemd units.

# ---- original file header ----
#
# @summary
#   Build dependency list for systemd units.
#
Puppet::Functions.create_function(:'docker_systemd::systemd_requires') do
  # @param args
  #   The original array of arguments. Port this to individually managed params
  #   to get the full benefit of the modern function API.
  #
  # @return [Data type]
  #   Describe what the function returns here
  #
  dispatch :default_impl do
    # Call the method named 'default_impl' when this is matched
    # Port this to match individual params for better type safety
    repeated_param 'Any', :args
  end


  def default_impl(*args)
    
    args = args[0] || {}
    container_deps =
      (args[:depends] || []).map { |dep| "docker-#{dep}.service"}
    systemd_deps = args[:systemd_depends] || []
    (systemd_deps + container_deps).join(' ')
  
  end
end
